---
---

# Spatial Data Wrangling 

:::objective
**Objectives**

In this module, you will:

* Introduction to spatial data concepts and operations
* Convert CSV lat/long to spatial points and geocode address
* Overlay points with boundary data, merge SDOH data, visualize as choropleth
:::

You've spent some time visioning your project goals, breaking down specific needs, and connecting with potential users of the application. Once you've done these things, you're ready to take on the data at hand, and start wrangling. Because we're working with place-based SDOH data, that means learning how to handle *spatial data.* Working with spatial data is like working with regular data, plus entirely new dimensions. The data formats are different, and you'll need different tools to work with it. 

## Environment Setup

Which computing environment should you work with spatial data? It's up to you — there are many options to choose from today. Our toolkit focuses on free and opensource tools, and/or tools that are widely available with low cost. In this chapter, we'll work with *QGIS*, *Excel*, and *GeoDa.* 

:::tools
For this module, you need the following installed on your machine. A recent, stable version is sufficient; note that versions will be updated regularly, so you'll need to learn to update, manage, and troubleshoot as you go. 

- **QGIS**: QGIS is a free, opensource geographic information system that can be used to create, map, and analyze geospatial data. Download QGIS [here](https://qgis.org/en/site/).
- **Excel**: Excel is a spreadsheet software that can store, organize, and analyze data sets. Use a free online version [here](https://www.microsoft.com/en-us/microsoft-365/free-productivity-apps#free-benefits).
- **GeoDa**: GeoDa is a free, opensource GIS tool, designed to be an introductory tool for spatial data science. Download GeoDa [here](https://geodacenter.github.io/).
:::

If you prefer to code, or want to practice coding, go to the Appendix to learn the same materials using the R Programming Language. 

Throughout, you'll learn the tool you're using isn't as important as your ideas, concepts, and goals. You can merge data, run a buffer analysis, and make a map using ESRI, QGIS, R, Python, Spatial SQL or any other number of software or coding languages. Your goal is to learn what you want to do, understand why you need to do it, and learn & discover as you go.

That being said, data wrangling takes up **at least 80%** of a traditional GIS/spatial analysis project. Don't underestimate the time needed to resolve challenges, and practice patience.

### Installing & Working with Software {-}

All three software that you'll be introduced to have extensive documentation to help users understand the tools available to them and troubleshoot issues they come across. This documention can be found [here](https://www.qgis.org/en/docs/index.html) for QGIS, [here](https://support.microsoft.com/en-us/excel) for Excel, and [here](https://geodacenter.github.io/documentation.html) for GeoDa. In addition to these official documentation sources, search engines are your best friend. There are forums dedicated to troubleshooting software issues, and someone else will have likely experienced your problem before. Searching the issue you run into or the error message that you receive is likely to bring up a forum thread of people who worked to resolve the same issue.

Another important aspect in working with this software is file management. Decide before you start a project what your file management strategy will be, and where everything will be stored. Some GIS software use directories, rather than storing data locally, meaning that the software needs to know where to access files. If a file gets moved mid-project, the software will be unable to access the data, and you'll have to re-add it to the project. Some file formats, like shapefiles, must also stay in the same folder as their associated files in order to be read correctly. A robust file management approach will save you time and frustration in the long run.

** add some background tips/advice on how to use documentation to figure stuff out.

** something about file management structures, installing your software here

** Tell ppl where the data for this workshop can be accessed (!!)

:::tip
**Installation Tip**

Mac users will need to override a security setting to download QGIS. Once you have installed QGIS, you will need to go to Security and Privacy in System Preferences. There, you will find a message that “1 GADL Complete.pkg” was unable to be opened. Select “Open Anyway.” You may need to do this for multiple packages depending on the version of QGIS you download. 

If you still have issues opening QGIS after this, Stack Overflow is a great resource for troubleshooting GIS software issues.
:::

### Troubleshooting {-}

Need to figure stuff out on your own, explain tips like using Google search (not Bing etc), link some primary resources

## Intro to Spatial Data 

Spatial data is essential for understanding the world around us, as it combines information with specific locations. This type of data is vital because it allows us to see how information changes with location. Without the geographical component, we're left with just a list, not a spatial analysis or map that can guide decisions or provide insights.

Understanding these aspects of spatial data is crucial, especially as we delve into more complex analyses. Whether it's navigating through the components of a shapefile or exploring data in R, having a grasp on these concepts can help tackle the challenges that come with spatial data analysis.

### Spatial Data Types {-}

*from our opioid toolkit below -- change up language a bit **

Two common formats of spatial data are vector and raster data. Vector data represents the world surface using points, lines, and polygons whereas raster data can be satellite imagery or other pixelated surface. The figure below demonstrates how vector and raster data models represent geographic space differently, where points, lines, and polygons consist of the essential basis of the vector data model.

** add cool drawing of points/lines/polygons

We mainly use vector data for our purpose. For example, a group of clinics can be geocoded and converted to points, whereas zip code boundaries are represented as polygons. Note that spatial data types include the basic attributes in addition to their spatial information. So points on a map correspond to associated details for each clinic provider, and may also include fields like “name”, “services”, and more. 

For example, a park can represented as a polygon or a point. Linked with each park, we can have information regarding their names, sizes, types of plants, open hours, and other various features. These attributes can be stored in a data table, along with their spatial inforamtion, in a shapefile, or a spatial file loaded in your R environment.

### More Types of Data {-}

While we focus on tabular spatial data in this introductory module, you may work with multiple types of data in your SDOH project that is linked to place. Another of thinking about this is considering spatial data as primary, secondary, or tertiary. In the following section, we will provide a brief description of each of these types of data.

<details markdown='1'><summary>**Primary Spatial Data**</summary>Primary spatial data refers to the data that you can collect either personally or through a sensor/machine which you or your stakeholders have previously installed. There are several examples of spatial visualizations of SDOH made with primary data. Some researchers have used online interviews or questionnaires to analyze their experiences in their neighborhood. Other researchers have placed sensors to map air quality in cities. The use of Global Positioning Systems (GPS) or smartphones is another way to generate primary data.</br></br></details>

<details markdown='1'><summary>**Secondary Spatial Data**</summary>You may encounter challenges when gathering SDOH primary spatial data, as it can be a time-consuming and costly endeavor. As a result, SDOH researchers, mapmakers, and advocates frequently turn to various secondary resources, such as spatial databases and census records, to inform their spatial representations. Typically, these files consist of digital layers that are prepared for seamless incorporation into a GIS or web mapping application. However, you can also work and manipulate non-spatial data in your project. Notable sources for such data include both profit and non-profit databases, government census information, and even digitized or scanned paper maps.</br></br></details>

<details markdown='1'><summary>**Tertiary Spatial Data**</summary>In the realm of SDOH spatial visualizations, there exists a third option–your map(s) may access other maps’ spatial data. Tertiary spatial data are spatial layers that have been previously or currently utilized in other cartographies and are readily accessible for integration into a Geographic Information System (GIS) or web mapping applications. When engaging with stakeholders experienced in health mapping, it's worth inquiring whether they possess any spatial layers that could prove beneficial for your project. </br></br></details>

It is key to emphasize that data can often be tainted by biases and errors. As a result, the methods used to gather, aggregate, or model spatial data can have adverse effects on the quality of our data visualizations. It is of utmost importance to meticulously scrutinize various forms of data, whether they are qualitative (e..g, interviews or questionnaires), quantitative (e.g., databases), or mixed (e.g., surveys). A valuable starting point for data analysis involves assessing metadata within databases or interview questions. Further insights into this subject will be explored in subsequent sections of this toolkit.

In your project, there's no need to limit yourself to just one kind of data. In fact, it's not only possible but often necessary to mix and match different sources and types of spatial data to craft compelling SDOH spatial visualizations.

:::activity
Review these projects below and identify what type of data they use. In your opinion, what other types of data could they use to enrich their visualizations? 

[Using Asset Mapping to Identify Health Needs of a Latinx Population in Rural Virginia](https://scholarscompass.vcu.edu/cgi/viewcontent.cgi?article=1396&context=uresposters)
[US Social Determinants of Health Atlas - Map of the Month](https://carto.com/blog/visualizing-health-data-social-factors)
:::


### Spatial Data Formats {-}

*from our opioid toolkit below -- change up language a bit **

Spatial data can be stored in a text file like comma-separated value (CSV) files. However, the text file needs to have essential location columns with latitude and longitude to represent the coordinate location of a spatial object. Furthermore, a CSV file with lat/long columns is only a flat/non-spatial file, until the spatial location context is enabled as a new spatial data format.

A common spatial data format is the shapefile, which comes from ESRI/ArcGIS proprietary software. The shapefile file format (`.shp` for short) includes a minimum of 4 files, with a common prefix and different filename extensions `.shp`, `.shx`, `.dbf`, and `.prj`. In order to work with the spatial data, we need all these four components of the shapefile stored in the same directory, so that the software or coding platform being used can know how to project spatial objects onto a geographic or coordinate space. Other common spatial data formats include the GeoJSON (or `.geojson`)or geopackage (or `.gpkg`). We'll work with shapefiles and GeoJSONs in this toolkit.

:::activity 
**Open a Spatial Vector File**

- Open up QGIS, and start a new project.
- Open the file `boundaries_chicago.geojson` as a new vector layer by navigating to Layer -> Add Layer -> Add Vector Layer, or through your local or network drives in the Browser panel.  ** make this part more clear; diff versions may be different)
- Double click or drag and drop the file into Layers.
<details markdown='1'><summary>**Add a Basemap**</summary>

You’ll need to download a plugin. The simplest basemap system is a part of the QuickMapServices plugin. Go to Plugins -> Manage and Install Plugins. Search QuickMapServices, and install it. Once installed, select Web -> QuickMapServices. Depending on your version of QGIS you may have different base map options, but all versions should at least have OSM Standard. Select this to add the base map. Alternatively, the OpenLayer plugin will also provide base map options.

<br/></details>

- Update stylings using Properties

**Challenge**: Repeat the same activity using GeoDa, a spatial statistical software.
:::

### Coordinate Reference Systems {-}

The Earth is an irregular ellipsoid, rather than a perfect sphere. As a result, many ways of visualizing the Earth, in whole or in part, have been developed. A Coordinate Reference System (CRS) communicates what method should be used to flatten or project the Earth’s surface onto a 2-dimensional map. Different CRS imply different ways of projections and can generate substantially different visualizations. For example, the following are some world maps using different projections:

*pic from slide 13 intro2spatialmed*

In addition to projections that optimize for global accuracy, there are many regional projections. For instance, NAD83 (North American Datum 1983) is divided into several UTM (universal transverse mercator) zones across the continent. So when projecting a data set of Illinois, for example, the most appropriate NAD83 projection would be NAD83 UTM zone 16N. Projection names have also been standardized to EPSG codes. The projection NAD83 UTM zone 16N is EPSG:26916.

Many data sets available online, and GeoJSON files as a general rule, default to the projection `EPSG:4326`, a global projection used by GPS. Changing projections can be critical for improving accuracy for your project, and making sure your layers are being displayed using the same information. Always search the internet to determine what projection is most appropriate for your project, and to find the corresponding EPSG code.

** explain why EPSG 4326 sucks, distance in degrees, why we have to change often **

:::activity 
**Change Projections in QGIS**

 Inspect the current projection. 
- In the bottom right corner of QGIS, the projection for the project as a whole will be listed as the EPSG code. Select this to change the projection. Since we’re working with a Chicago data set, let’s change the projection to EPSG:26916. 

*screencap available: 1projection*

Notice how the shape of the city boundary changed, now that the projections are not in agreement. Inspect the projection for the boundary layer by right clicking on the layer and going to Layer CRS. The current projection should be EPSG:4326. Since the project is now in EPSG:26916, you should see the option Set to EPSG:26916. Now you can see the boundary shape has changed again with the projections being back in agreement. 
:::

** Need to explain why we are changing projection, and tips on how to do that**


## Converting to Spatial Data

A common goal in SDOH research is to work address-level data, known as *points* or *events* (when considering time) in spatial analysis research. This could refer to resources in a community, . Before we can run any analytics on the resource location data, we need to convert resource addresses to spatial data points, which can be then used to calculate access metrics.

Locations, when measured as points, can include things like:

- **Health providers**: Hospitals, Clinics, Pharmacies, Mental health providers, Medication for opioid use disorder providers
- **Area resources**: Grocery stores & Supermarkets, Playgrounds, Daycare centers, Schools, Community centers
- **Area challenges**: Crime, Superfund sites, Pollution-emitting facilities

Points can also represent people, like individual patients residing in an area. Because individual locations for persons is protected health information, we’ll focus on point data as resources in the chapter. However, you can reuse the approach in this workshop to wrangle patient-level data the same way in a secure environment, under the guidance of your friendly IRB ethics board.

Let's start with an example where the spatial coordinate information has already been embedded within the data set as latitude and longitude information.

### Convert CSVs to Spatial Data 

Comma separated (CSV) files are not spatial data; they may *contain* spatial data, but to be used for spatial analysis or mapping they will need to be converted to a spatial data format, such as a `GeoJSON` or `shapefile` data format. As long as a CSV contains spatial data, GIS software should allow you to save CSV data as a new spatial data file. 

There are multiple options for converting CSV files to spatial data without code using opensource software like QGIS or GeoDa.For this type of conversion, you’ll want a CSV file with coordinate information (e.g. longitude and latitude) in separate fields. 

** long/lat = x/y, not the other way

** need to know the CRS -- if you don't, try 4326, but keep in mind in may not be correct

:::activity
**Convert CSV to GeoJSON in QGIS**

<details markdown='1'><summary>**Step 1: Open a CSV File**</summary>
- Open your CSV file via Layer -> Add Layer -> Add Delimited Text Layer. We’ll use `Affordable_Rental_Housing_Developments.csv` for this exercise. 
- You will be prompted to indicate which fields in your CSV contain longitude and latitude (or some other X/Y coordinate system), as well as the CRS, which will likely (although not always!) be EPSG:4326 if not otherwise noted. Select the appropriate fields, then hit OK. 

*screencap available: 2csvtojson*

- A map of your data will be generated. 

<br/></details>

<details markdown='1'><summary>**Step 2: Add a Basemap**</summary>

Add a basemap to inspect that your data has loaded properly. If you've mixed up longitude and latitude, your data points may be on the other side of the world!

<br/></details>

<details markdown='1'><summary>**Step 3: Save in a Spatial Data Format**</summary>

Right click the layer and go to Export -> Save Features As. When you select a file path, you will be prompted to select a file format. Select GeoJSON and the appropriate file path. Once you save, you should have a new GeoJSON file. You could have saved this file using any other spatial format, too!

*screencap available: 3csvtojsonsave*

<br/></details>

** Challenge: Open a CSV as a spatial data file in GeoDa, then save as a shapefile.

:::

** Always be sure to inspect your data after conversion. If it's not plotting correctly (check with base map), you may have gotten coordinate order wrong, or used the wrong CRS. 


### Geocode Addresses

If you start with only addresses, you’ll need to geocode!

Addresses are not spatial data. They are real-world representations of spatial data, but GIS software will not be able to map them without further information. Geocoding is the process of converting addresses into geographic coordinates using a known coordinate reference system (CRS). We can then use these coordinates (ex. longitude, latitude) to spatially enable data. 

** Explain that there are multiple geocoding services available, with varying quality. How precise does your measure need to be? Do you want to reject matches with <90% uncertainty? If you're at a university or public sector setting, you may have access to ESRI geocoding services... Also note how you should NEVER geocode sensitive data as it's not HIPPA protected unless on a compliant server... 

** After determining the service, plan for data cleaning/preparation stage, matching goals

** redo following section as tool-neutral tips : Geocoding tools may be having an issue reading some addresses due to formatting issues in the CSV. Suite or apartment numbers, for example, may cause tools to be unable to geocode addresses. Only include the street address in the address column of your CSV. If you want to retain apartment or suite numbers, include them in a separate column in your CSV. Another common issue is an address being miswritten in your CSV file. Even something as small as an extra apostrophe can prevent an address from being geocoded properly. Many cities have also addresses that are duplicates or are very similar. Providing  the most information you can is the best way to resolve this issue. Geocoding tools can use street address, city, state, and country information to geocode addresses. If you do not already have all of this information in your original CSV, add it and try geocoding again.


:::activity

**Geocode with QGIS**

For this exercise, download `chicago_methadone_nogeometry.csv`, a data set of methadone centers in Chicago that only includes center names and addresses.

<details markdown='1'><summary>**Step 1: Geocode with MMQGIS**</summary>

To geocode addresses in QGIS, first you will need to install the plugin MMQGIS. Go to Plugins -> Manage and Install Plugins. Search MMQGIS, and install it. 

*screencap available: 4mmqgis*

Once installed, the plugin should be visible on the toolbar across the top. Select MMQGIS -> Geocode -> Geocode CSV with Web Service.

*screencap available: 5geocodepathway*

Upload your CSV file. Confirm the correct fields are being read, choose your web service (OpenStreetMap is the open source option), name your output files and select the file formats. Hit apply, and the addresses should appear as points, and a spatial data file should have been generated and appear on the left side of your screen as a new layer.

*screencap available: 6geocodeparameters*

<br/></details>

<details markdown='1'><summary>**Step 2: Inspect your Data**</summary>

Once all your addresses are appearing, inspect them to ensure that everything has geocoded properly. Add a basemap to quickly visually inspect your data points. From the layers sidebar, right click your geocoded spatial data file and select Zoom to Layer(s). If any data points lie outside your expected spatial extent, this will quickly alert you to that issue. 

Inspect the layer attribute table to determine the source of any issues. Right click your geocoded layer and select Open Attribute Table. In addition to the information from your CSV, QGIS will have generated a few more pieces of information, including the full address and lat/long. Taking a look at this information for any points that did not properly geocode can help you discover where the issue may be in your original CSV. 

<br/></details>

Once everything has geocoded properly, you’ll have a spatial data file ready to use in other software.
:::


## Merge data sets

Merging data sets is a vital skill for analyzing health data from an SDOH perspective. SDOH data and health data will often be in separate data sets, but use the same geographic scale, such as zip code or census tract. Being able to merge these kinds of data sets together using that scale is important to the ease of performing analysis with your data.

### Reshape Data {-} 

data sets often don’t come in GIS-friendly formats. Data may be separated vertically among multiple variables rather than horizontally along a single identifying variable. To merge data to boundaries, we'll have to reshape from long to wide format.

Long data formats have repeating values in the first column, compared to wide data formats which do not. Long formats are preferred in epidemiology work, but wide formats are needed for spatial data, making conversions between the two especially important in the realm of health geography.

-- explain long vs wide data formats

-- long preferred in epi work

-- wide formats needed to spatial data

:::activity

**Long to Wide with Excel**

File: COVID-19_Cases__Tests__and_Deaths_by_ZIP_Code.csv 

To create a wide data set with the cumulative cases for each week for each zip code, create a pivot table in Excel. 

<details markdown='1'><summary>**Step 1: Create a Pivot Table**</summary>

- Open the CSV as an excel file, and open a new sheet. 
- Go to Insert -> Pivot Table. 
- Select the data you wish to include; in this case, we want the cumulative case data, so select columns A-F from the original excel sheet. 
- Make sure the pivot table will be placed in the new excel sheet, and hit OK. 

<br/></details>

<details markdown='1'><summary>**Step 2: Add Your Data**</summary>

The pivot table will open with the selected data, which can be sorted into rows, columns, values, and filters. 
- In this example, the zip codes should be our rows, so choose Zip Code from the selection and drag it into Rows. 
- We want our columns to be organized by week, so drag either Week Number, Week Start, or Week End into the Columns. 
- You’ll notice these variables split into multiple categories when dragged into a pivot table field. Use the information icon at the side of each category unwanted information. 
- Finally, drag Cases - Cumulative into the Values to fill out the table.

<br/></details>

<details markdown='1'><summary>**Step 3: Clean Up Your Table**</summary>

Pivot tables often generate columns and rows that are unnecessary for our purposes. These extra columns and rows could make it difficult for spatial software to read your CSV later.

- Use the drop down menu for Row Labels or Column Labels to remove any unwanted rows or columns, such as Grand totals and the first row that includes Sum of Cases and Column Labels.  
- Rename the column containing zip codes. 

<br/></details>

Your completed pivot table will look something like this:

*screencap available: 8pivotresult*

Save the sheet as a new CSV by going to File -> Save As. It's ready for merging!

**Note**: You can also select variables of interest as a subset of the data using QGIS or GeoDa.
:::


### Join by Attribute {-}

You will come across data with various different boundaries, such as county, zip code, and census tracts. Some cities, like New York and Chicago, have developed additional neighborhood boundaries that aggregate census tracts. Zip codes are particularly common for health data despite SDOH data typically being available at the tract level. This is to protect privacy, but it is something to be cautious of because these larger scale boundaries tend to contain a lot more variation in SDOH measures than finer scale boundaries. Associations that may appear if using tract-level data could be hidden at the zip code level. Data sets will need to use the same boundaries in order to be merged using that information. 

** explain about different boundaries, warning in usage of zip code

** explain about finding a Key between data sets to merge; note on how to ensure data types are similar between

** explain how data needs to have a 1:1 merge to be succesful, and what to do if that's off

:::activity

** Merge SDOH data to Zip Codes in GeoDa **

Here, we’ll merge data sets with a common variable using GeoDa. Merging the cumulative case data set you created in the last section to zip code spatial data will allow you to map the case data. You’ll be merging the case data and spatial data using the zip codes field of each dataset. 

<details markdown='1'><summary>**Step 1: Clean Zip Code Data**</summary>

We've cleaned our covid case data already, but you’ll notice that the zip codes are repeated in the zip code data set, and needs to be cleaned before we can continue with merging the data. 

- Select one row for each zip code and save the selection as a new geojson, ChiZipCleaned. 

You’ll notice that two zip codes have repeats that are not exactly alike. This is because these two zip codes have small exclaves, and so are listed separately since they are separate polygons. However, having the repeated zip code will create problems when merging the data, and the exclaves are small enough not to be relevant for our analysis. Only choose the rows with a larger area for these two zip codes.

<br/></details>

<details markdown='1'><summary>**Step 2: Merge Data**</summary>

- Open ChiZipCleaned.geojson. 
- Go to Table -> Merge. 
- Select the cumulative case data set. 
- Under parameters, select Merge by key values, with zip selected for current table key and Zip Code selected for import table key. 
- Move over all data columns you want to see in this merged data set.

Tip: you do not need to include Zip Code since this field is being used to merge the two data sets, including it will only duplicate zip codes in the resulting data set.

*screencap available: 9mergeparameters*

<br/></details>

** Challenge: Do the same process using QGIS.
:::

### Join by Location {-}

** Sometimes, you won't have a boundary key.. 

** A spatial join is defined as ...

Add spatial joins to data to analyze the relationships data sets may have with each other. This tool allows you to merge certain aspects of data sets, such as joining descriptive statistics about one data sets relation to the other.

:::activity
** Add a Spatial Join **

We’ll create a spatial join with affordable housing development data and ChiZipCleaned.geojson. In this case, we’ll add the number of affordable housing developments in each zip code to the zip code data set.

<details markdown='1'><summary>**Step 1: Join Attributes**</summary>

Go to Processing -> Toolbox and search for Join Attributes. For this exercise, select Join attributes by location (summary). Set the following parameters:

*screencap available: 13joinparameters*

These parameters are set on the premise that we want a count of the affordable housing developments contained within each zip code. A new joined layer will be mapped on top of your current layers. 

<br/></details>

<details markdown='1'><summary>**Step 2: Map the Joined Data**</summary>

The new layer generated by the spatial join will default to a single symbol map, not providing any useful visual information about the spatial join.

- Change the symbology by right clicking and going to Properties -> Symbology.
- Change the symbology from Single Symbol to Graduated with the value Community Area Name_count. 

Try changing the color ramp, mode, and number of classes. The resulting joined layer may look similar to the one below.

*screencap available: 14joinmap*

*Note: In order for null values to appear, you may need to first set symbology to graduated colors, then change it to Rule-based. Add a field with the rule set to Else rather than Filter. Then change colors and arrange as you wish.* 

<br/></details>
:::

:::pitfall
**Pitfall**

Invalid Geometries

Zip code 60655 has an enclave not included in the Chicago city limits, and you may have a technical issue with that enclave when moving between GeoDa and QGIS with the newly cleaned Chicago zip code data that causes an Invalid Geometry error when conducting a spatial join. Since the zip code in question has no affiliated affordable housing developments, in this case we’ll set the Invalid feature filter, found under the layer’s Advanced Options when creating the spatial join, to skip features with invalid geometries.
:::

## Inspect Data 

** Once you've merged data, you'll want to inspect and visualize with simple views.

Inspect data, both through spatial and non-spatial means, when starting a new project. This helps verify that all data wrangling to this point has occurred properly. In the next module, we'll dive into the details of this further, moving past inspection to data analytics.

### Thematic Maps {-}

To inspect data from a spatial perspective, create a series of choropleth maps. ** Briefly exlain this without too much detail **

### Map Overlay {-}

Overlay multiple data sets to investigate how they correspond to one another. Open the data sets you are interested in and order your layers appropriately to get an initial view of potential relationships between data sets.

:::activity
** Inspect Data with Different Methods **

<details markdown='1'><summary>**Generate Choropleth Maps in GeoDa**</summary>

Open ChiZipCleaned.geojson. From the Map option on the toolbar, you can select a variety of choropleth map options using different variables or breaks for your data. 

Select a mapping method and a variable to map. Inspect your data by comparing how different data break methods present the same variables, and how the spatial patterns of different variables compare. 

*Screencap available: 10choroplethmaps*

<br/></details>

<details markdown='1'><summary>**Overlay Data in GeoDa**</summary>

With the Chicago zip code data already loaded in GeoDa, add a layer of point data with Affordable_Rental_Housing_Developments.csv. 

- From the map view, select Add Map Layer. 
- Select the affordable housing data set, set the lat/long fields, and hit OK. 
- If you do not see the housing data, go to Map Layer Settings. Make sure the layer is turned on and ordered first.

Once you add it to one map, you should be able to find it as a layer in each subsequent map you make with these data sets for the duration of your mapping session.

Note: the first row does not have lat/long data and may impede GeoDa from mapping the rest of the affordable housing data set. If you have this problem, try removing this row from the CSV.

*Screencap available: 11overlaymap*

<br/></details>

<details markdown='1'><summary>**Overlay Data in QGIS**</summary>

Let’s overlay zip code boundary data with affordable housing point data.

- Load ChiZipCleaned.geojson into QGIS. 
- Add Affordable_Rental_Housing _Development.csv by going to Layer -> Add Layer-> Delimited Text Layer.
- Navigate to the file, and ensure all fields indicate the correct data source in order to display the data properly.

*screencap available: 12qgisoverlay*

Adjust the color, transparency, size, and borders of each layer by right clicking the layer and going to Styles -> Edit Symbol. The affordable housing data can also be saved as a spatial data set at this point, by right clicking on the layer and navigating to Save Features As. 

<br/></details>
:::

## Finding Data

In this module, we provided sample data to work with. When you're looking for your own data, ....

** Determine your spatial boundary - get boundary data. Use that as your master file to merge in more.

** Use a conceptual model to guide your variable selection.

** Use existing resources that have aggregated cleaned data to access; or, extract from the Census directly

** OSM data for international work

## Resources {-}
