# References {-} 

## Module 1 {-}

- Agency for Healthcare Research and Quality. (n.d.).  Data Visualizations https://www.ahrq.gov/data/data-visualization/index.html

- Appsilon. (n.d.). Air Quality vs Respiratory Disease. https://connect.appsilon.com/air-quality/

- Babinski, G. (2021).  GIS&T for Equity and Social Justice.  The Geographic Information Science & Technology Body of Knowledge (2nd Quarter 2021 Edition), John P. Wilson (ed.). DOI: 10.22224/gistbok/2021.2.2

- Centers for Disease Control and Prevention’s Division for Heart Disease and Stroke Prevention. (2017, August). Types of thematic maps. Tips for Creating Maps for Public Health. https://www.cdc.gov/dhdsp/maps/gisx/resources/thematic-maps.html

- Centers for Disease Control and Prevention’s Office of Health Equity. (2022, July). What is health equity? https://www.cdc.gov/healthequity/whatis/index.html. 

- Centers for Disease Control and Prevention’s Office of Health Equity. (2022, December) Social Determinants of Health.  https://www.cdc.gov/about/sdoh/index.html

- City Health Dashboard. (2021, July). New Video Series: Moving from Data to Action. https://www.cityhealthdashboard.com/blog-media/1501

- Chandra A, Martin LT, Acosta JD, Nelson C, Yeung D, Qureshi N, Blagg T. Equity as a Guiding Principle for the Public Health Data System. Big Data. 2022 Sep;10(S1):S3-S8. doi: 10.1089/big.2022.0204. PMID: 36070506; PMCID: PMC9508440.

- Douglas JA, Subica AM, Franks L, Johnson G, Leon C, Villanueva S, et al. Using Participatory Mapping to Diagnose Upstream Determinants of Health and Prescribe Downstream Policy-Based Interventions. Prev Chronic Dis 2020;17:200123. DOI: http://dx.doi.org/10.5888/pcd17.200123

- Golebiowska, I., Korycka-Skorupa, J., and Slomska-Przech, K. (2021). Common Thematic Map Types.  The Geographic Information Science & Technology Body of Knowledge (2nd Quarter 2021 Edition), John P. Wilson (ed.). DOI: 10.22224/gistbok/2021.2.7

- Hessler J, Discenza C, Fenn Gilman A,.(2023).The Mapping of Race in America. https://storymaps.arcgis.com/stories/ac998a8425b54e319f61d34ff1a94a0c 

- Leadership Conference Education Fund (2023). Data for Equity: A Review of Federal Agency Equity Action Plans. https://civilrights.org/wp-content/uploads/2023/04/Data-For-Equity-Report.pdf 

- Kelly, M. (2022). Narrative and Storytelling. The Geographic Information Science & Technology Body of Knowledge (2nd Quarter 2022 Edition), John P. Wilson (Ed.). DOI: 10.22224/gistbok/2022.2.12.

- Kolak M, Bhatt J, Park YH, Padrón NA, Molefe A. (2020) Quantification of Neighborhood-Level  Social Determinants of Health in the Continental United States. JAMA Network Open.;3(1):e1919928. doi:10.1001/jamanetworkopen.2019.19928

- Kolak, M., Li, X., Lin, Q., Wang, R., Menghaney, M., Yang, S., & Anguiano Jr, V. (2021). The US COVID   Atlas: A dynamic cyberinfrastructure surveillance system for interactive exploration of the pandemic. Transactions in GIS, 25(4), 1741-1765.

- Robert Wood Johnson Foundation (2023). Achieving Health Equity. https://www.rwjf.org/en/building-a-culture-of-health/focus-areas/Features/achieving-health-equity.html

- SAMHSA’s Trauma and Justice Strategic Initiative (2014, July) SAMHSA’s Concept of Trauma and Guidance for a Trauma-Informed Approach.

- The Stavros Niarchos Foundation (2021, April) Health initiative progress update. https://uploads.knightlab.com/storymapjs/ddf1b1212ec9c9aac4bebe45196b367d/hi-update-english/index.html

- Pinkus A. (2021) Mapping Climate Risks by County and Community. https://www.americancommunities.org/mapping-climate-risks-by-county-and-community/

- Prestby, T. (2021). Characterizing Storytelling in COVID-19 Cartographic Journalism. Abstracts of the ICA, 3, 245.

- Santilli A, Carroll-Scott A, Wong F, Ickovics J, “Urban Youths Go 3000 Miles: Engaging and Supporting Young Residents to Conduct Neighborhood Asset Mapping”, American Journal of Public Health 101, no. 12 (December 1, 2011): pp. 2207-2210. https://doi.org/10.2105/AJPH.2011.300351

- University of Illinois. (2023). Eat. Move. Save. https://eat-move-save.extension.illinois.edu/#food-finder

- The Urban Institute. (2024). Do No Harm Guide: Crafting Equitable Data Narratives https://www.urban.org/projects/do-no-harm-project 


## Module 2 {-}

- Centers for Disease Control and Prevention. (2022) Heart Disease Death Rates, Total Population Ages 35+

- Chiang, Y-Y. and Lin, Y. (2020). Design, Development, Testing, and Deployment of GIS Applications.  The Geographic Information Science & Technology Body of Knowledge (4th Quarter 2020 Edition), John P. Wilson (Ed.). DOI: 10.22224/gistbok/2020.4.2 

- The Data Foundation. (n.d.) Data Maturity Assessment. https://data.org/dma/ 

- HealthIT.gov (n.d.) Stakeholder Responsibilities and Role Descriptions.  https://www.healthit.gov/sites/default/files/cds/3_5_14_stakeholder_responsibilities_and_role_descriptions.pdf 

- McKinsey & Company (2019) United States of Health Dashboard. https://www.mckinsey.com/industries/public-sector/our-insights/us-public-health-dashboard

- Minnesota Department of Health. (2023). Objectives and goals: Writing meaningful goals and SMART objectives. https://www.health.state.mn.us/communities/practice/resources/phqitoolbox/objectives.html 

- NCFDD. (n.d.). The NCFDD Mentor Map. https://www.ncfdd.org/ncfddmentormap

- Santilli A, Carroll-Scott A, Wong F, Ickovics J, “Urban Youths Go 3000 Miles: Engaging and Supporting Young Residents to Conduct Neighborhood Asset Mapping”, American Journal of Public Health 101, no. 12 (December 1, 2011): pp. 2207-2210. https://doi.org/10.2105/AJPH.2011.300351

- Soma, T., Shulman, T., Li, B., Bulkan, J., & Curtis, M. (2022). Food assets for whom? Community perspectives on food asset mapping in Canada. Journal of Urbanism: International Research on Placemaking and Urban Sustainability, 15(3), 322-339.

- Tulsa Health Department.  (2024, January 30) Data and stats https://tulsa-health.org/services/public-safety-and-data-services/data-and-stats/

## Module 3 {-}

- Data Foundation (2023) Stakeholder Engagement Toolkit for Evidence Building. https://www.datafoundation.org/stakeholder-engagement-toolkit-for-evidence-building-introduction

- Figma (n.d.) How to create a persona. https://www.figma.com/resource-library/how-to-create-a-persona/

- Interaction Design Foundation (2021) How to Conduct Focus Groups. https://www.interaction-design.org/literature/article/how-to-conduct-focus-groups

- Interaction Design Foundation (2024) Card Sorting: The Ultimate Guide. https://www.interaction-design.org/literature/article/the-pros-and-cons-of-card-sorting-in-ux-research

- Nielsen Norman Group (2024) 10 Usability Heuristics for User Interface Design. https://www.nngroup.com/articles/ten-usability-heuristics/

## Module 4 {-}

- https://www.opengeomatics.ca/topology-and-geocoding.html#geocoding 

## Module 5 {-}

- [GeoDa Documentation](https://geodacenter.github.io/documentation.html) remains an ESDA standard to uncover dozens of techniques for discovery.

- Brewer, C. (2016). Designing Better Maps: A Guide for GIS Users, 2nd Edition. ESRI press.

- D'ignazio, C., & Klein, L. F. (2023). Data feminism. MIT press.

- [Center for Spatial Data Science (2024). Scientific Reasoning in Spatial Data Science Education Project. University of Chicago: Center for Spatial Data Science.](https://spatial.uchicago.edu/education/scientific-reasoning)

- Krygier, J., & Wood, D. (2016). Making maps: a visual guide to map design for GIS. Guilford Publications.

- Peterson, G. N. (2020). GIS cartography: a guide to effective map design. CRC Press.

## Module 6 {-}
